
version: '3'

services:

    DC3N1:
        container_name: container_cass_cassandra-3.11.13_executor_uuid_N1
        image: image_cassandra_cassandra-3.11.13
        command: bash -c 'sleep 0 && /usr/bin/supervisord'
        networks:
            network_cassandra-3.11.13_to_cassandra-4.0-alpha1_stressTest_dc1ring:
                ipv4_address: 252.11.1.2
        volumes:
            - ./persistent/data/n1data:/var/lib/cassandra
            - ./persistent/log/n1log:/var/log/cassandra
            - ./persistent/consolelog/n1consolelog:/var/log/supervisor
        environment:
            - CASSANDRA_CONFIG=/cassandra/conf
            - CASSANDRA_CLUSTER_NAME=dev_cluster
            - CASSANDRA_SEEDS=252.11.1.2,
            - CASSANDRA_LOGGING_LEVEL=DEBUG
        expose:
            - 7000
            - 7001
            - 7199
            - 9042
            - 9160
            - 18251
        ulimits:
            memlock: -1
            nproc: 32768
            nofile: 100000

    DC3N2:
        container_name: container_cass_cassandra-4.0-alpha1_executor_uuid_N2
        image: image_cassandra_cassandra-3.11.13
        command: bash -c 'sleep 0 && /usr/bin/supervisord'
        networks:
            network_cassandra-3.11.13_to_cassandra-4.0-alpha1_stressTest_dc1ring:
                ipv4_address: 252.11.1.3
        volumes:
            - ./persistent/data/n2data:/var/lib/cassandra
            - ./persistent/log/n2log:/var/log/cassandra
            - ./persistent/consolelog/n2consolelog:/var/log/supervisor
        environment:
            - CASSANDRA_CONFIG=/cassandra/conf
            - CASSANDRA_CLUSTER_NAME=dev_cluster
            - CASSANDRA_SEEDS=252.11.1.2,
            - CASSANDRA_LOGGING_LEVEL=DEBUG
        depends_on:
                - DC3N1
        expose:
            - 7000
            - 7001
            - 7199
            - 9042
            - 9160
            - 18251
        ulimits:
            memlock: -1
            nproc: 32768
            nofile: 100000

networks:
    network_cassandra-3.11.13_to_cassandra-4.0-alpha1_stressTest_dc1ring:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 252.11.1.1/24
